version: '3.7'

services:
  users-service:
    image: node:latest
    command: npm run dev
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - '4001:4001'

  users-database:
    image: mongo:latest
    volumes:
      - ./configuration/database/:/data/db
